name: Release caddy-cf docker

on:
  #repository_dispatch:
  workflow_dispatch:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set env
      run: |
        echo "TAG=$(cat tag)" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          TAG=${{ env.TAG }}
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cf:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/caddy-cf:${{ env.TAG }}
